### ISSUE TITLE
Support for discrete distributions

### ISSUE THREAD

**Issue by tnagler** [JonasMoss/univariateML#26]
Would be nice to support some distributions with discrete support (like Poisson or Binomial). Are there any reasons to not support them in this package? I might work on a PR at some point, but wanted to check with you first.

P.S.: Great, great package! I always wanted to do something like that, but never got around to it. Relieved that I can cross that off my list ;)

**Comment by JonasMoss** [comment]
Thanks a lot!

I don't think there is a strong reason not to include discrete distributions. As far as I remember I have restricted this project to densities not to be overburdened. In fact, I can only think of the following to keep in mind if you / I were to implement discrete ML estimators.

- Adding an attribute to the `univariateML` class stating the model is discrete;
- Modifying the plot and summary generic.

Probably stuff like the `qqplot`, `d**`, `p**`, `q**`, and `r**` functions would work without modification.

So yeah, don't hesitate on that PR! =)

**Comment by tripartio** [comment]
I echo the thanks for the great package, but Is there any progress on this? I too, am surprised to find discrete distributions like Poisson and negative binomial missing.

**Comment by tripartio** [comment]
Since there seems to be no progress on this, I am also considering implementing some missing distributions of possible and then offering a PR. I'm thinking in particular of discrete distributions like Poisson and negative binomial.

Please point me to a template implementation in your code that could be modified towards this end. And, very importantly, please explain some crucial tests that need to be done while developing to ensure the implementation is correct.

**Comment by JonasMoss** [comment]
Great to hear @tripartio !

## Thoughts
* I suggest adding an attribute `attr(object, "continuous") = False` then check for missingness of this argument in the generic functions where relevant (alternatively we may add this attribute to all functions. boring but only a couple of minutes.)
* Poisson and negative binomial, and binomial as well, have "easy" supports (intervals of natural numbers). So I don't think the support functionality needs to be changed.
* Maybe the probability plot doesn't make sense for discrete distributions? Not sure.

## Tests
* The tests for the `ml*` functions are mostly boilerplate; it should be reasonably easy to get the gist of them by looking at an example. https://github.com/JonasMoss/univariateML/blob/master/tests/testthat/test_mlexp.R
* It's natural to add explicit discrete distributions to all tests such as https://github.com/JonasMoss/univariateML/blob/master/tests/testthat/test_functions.R.  The tests not starting with `ml` mostly follow the same template: I test the functions using one or a couple of randomly chosen continuous distributions. Just add, e.g., poisson to test functions and follow the already existing logic. It could be helpful to make a checklist here, enumerating whichever of the test files have been appropriately modified. Many of these tests are boilerplaty and boring, and shouldn't be hard to modify.
* At least one test (https://github.com/JonasMoss/univariateML/blob/master/tests/testthat/test_input_checks.R) should work by itself, since it runs across all defined densities.

I hope this is enough to get started! Just ask / explain if there's something.

**Comment by tripartio** [comment]
Thanks for the details. I won't have the time to do this just yet, but your comments provide a roadmap so that I can start adding additional tests as I need them.

**Comment by tripartio** [comment]
I've finally got around to trying to implement some discrete distributions. I forked the repository and I started with something really easy: the Poisson distribution. When I complete it, I'll submit a pull request so that you can verify if I've done things right and according to your coding style. Overall, I congratulate you on your very clear code which I've found quite easy to follow!

I'm pretty advanced with the initial Poisson implementation (I've implemented `mlpois()` and its corresponding tests, but before I submit my first PR, I have a few questions. I'm using `mlnorm` as my template.

**First**, I understand the "support" attribute to mean the domain of allowed values. (Please correct me if I'm wrong.), So, i currently have `attr(object, "support") <- c(0, Inf)`. However, strictly speaking, these are double values whereas Poisson values are strictly integers. Does this matter? The difficulty here is that while `0L` can be an integer, I understand that `Inf `in R is only a double. This issue comes up in `test_mlpois.R`, which currently has 

```
## Check support.
expect_equal(class(attr(est, "support")), "numeric")
```

Should that instead be `expect_equal(class(attr(est, "support")), "integer")`?

**Second**, I don't understand your comment above, 

> It's natural to add explicit discrete distributions to all tests such as https://github.com/JonasMoss/univariateML/blob/master/tests/testthat/test_functions.R.

Unless I'm mistaken, all the code there applies only to `mlnorm()`, not to any other distribution. What am I supposed to do with that test file for the Poisson distribution?


**Third**, please note that I am not even going to attempt to take on plots just yet. These are probably non-trivial. But if you have some concrete ideas what equivalent discrete plots might look like for now, please let me know. Or at least what code needs to be modified to fail gracefully if users ask for discrete plots that have not (yet) been implemented.


**Fourth**, for the all-important log-likelihood formulas, please note that I'm not a statistician--I'm more of a computer scientist. So, I have to hack statistical formulas together. So, I used ChatGPT to get the formula for Poisson:

`attr(object, "logLik") <- -n * lambda + sum(x) * log(lambda) - sum(lgamma(x + 1))
`

Fortunately, we have the stats package functions for comparison, so I verified that the formula is accurate:

`sum(stats::dpois(x, lambda, log = TRUE))
`

 I will always implement such testing verification.

On a sidenote, I initially wondered why your code calculates log-likelihood with formulas like `attr(object, "logLik") <- -n / 2 * (1 + log(2 * pi) + 2 * log(sigma))` rather than directly using `dnorm()` as in the tests. But when I used microbenchmark to compare both versions, I found that the formula is twice as fast (at least, in the case of `mlpois()`. So, I guess this is for speed. I followed suite.


Please give me your responses for the first two points (optionally comment on the latter two); I should then be able to complete my first PR so that you can see if I've got the template right.

**Comment by tripartio** [comment]
Also, when I run full tests, I get the following warnings. However, this is not code that I created or changed, so I will ignore it, assuming that it is an existing issue in the code that I forked from today:

```
✔ |   2     10 | model_select [1.4s]                                                                                     
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning (test_model_select.R:19:1): (code run outside of `test_that()`)
NaNs produced
Backtrace:
     ▆
  1. ├─testthat::expect_equal(...) at test_model_select.R:19:1
  2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
  3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
  4. ├─stats::coef(model_select(small_data))
  5. └─univariateML::model_select(small_data)
  6.   └─base::lapply(mlf, function(f) try(f(x, na.rm = na.rm), silent = TRUE)) at univariateML/R/model_select.R:45:3
  7.     └─univariateML (local) FUN(X[[i]], ...)
  8.       ├─base::try(f(x, na.rm = na.rm), silent = TRUE) at univariateML/R/model_select.R:45:3
  9.       │ └─base::tryCatch(...)
 10.       │   └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 11.       │     └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 12.       │       └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 13.       └─univariateML (local) f(x, na.rm = na.rm) at univariateML/R/model_select.R:45:3

Warning (test_model_select.R:19:1): (code run outside of `test_that()`)
NaNs produced
Backtrace:
     ▆
  1. ├─testthat::expect_equal(...) at test_model_select.R:19:1
  2. │ └─testthat::quasi_label(enquo(expected), expected.label, arg = "expected")
  3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
  4. ├─stats::coef(model_select(c(small_data, NA), na.rm = TRUE))
  5. └─univariateML::model_select(c(small_data, NA), na.rm = TRUE)
  6.   └─base::lapply(mlf, function(f) try(f(x, na.rm = na.rm), silent = TRUE)) at univariateML/R/model_select.R:45:3
  7.     └─univariateML (local) FUN(X[[i]], ...)
  8.       ├─base::try(f(x, na.rm = na.rm), silent = TRUE) at univariateML/R/model_select.R:45:3
  9.       │ └─base::tryCatch(...)
 10.       │   └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 11.       │     └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 12.       │       └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 13.       └─univariateML (local) f(x, na.rm = na.rm) at univariateML/R/model_select.R:45:3
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by JonasMoss** [comment]
> First, I understand the "support" attribute to mean the domain of allowed values. (...)

I don't think this is a problem, floaty `Inf`s are fine, and probably the only reasonable R-ish option. (We don't want to create a class or something only to contain possible plus-minus inf for integers.) I also don't think the functions work with longs internally, as longs are virtually never used in R, even for integers - double floats are used instead. So float is fine.

Btw, R is constructed so that `is.numeric(1L)` equals `TRUE`. So integers *are* numerics, despite their class being "integer". Whatever :p

> Second, I don't understand your comment above (...)

The tests are about the functions `pml`, `qml`, and so on. I tested them only for `lnorm` here, probably when I made the functions. The corresponding tests for, e.g., Poisson would check that the automatically generated density (pmf), distribution, quantile, and random number generating functions work. There probably won't be any difference, but will be nice to check this once.

> Third, please note that I am not even going to attempt to take on plots just yet. 

No problem! Feel free to submit a pull request without plots, I can implement those myself. 

> Fourth, for the all-important log-likelihood formulas, please note that I'm not a statistician--I'm more of a computer scientist. So, I have to hack statistical formulas together. So, I used ChatGPT to get the formula for Poisson:

That's fine. Yeah, the log-likelihoods are implemented this way only for speed. But the gain is so marginal it's no problem not doing it.

**Comment by tripartio** [comment]
I've created the PR to support the Poisson distribution: https://github.com/JonasMoss/univariateML/pull/51. I've run a full `testthat` tests and all tests passed (except for the warning that I mentioned above). Please review my code and let me know changes that need to be made before it can smoothly integrate with the codebase. 

The one significant change that I made to existing code is that I completely rewrote `test_functions.R` so that it can be generic for both the normal and Poisson distributions, with a template for adding automated testing for other restrictions by specifying just one line of code to add each one. I hope this matches the intention of your original code.
