### ISSUE TITLE
mlnaka() does not ensure parameter bounds

### ISSUE THREAD

**Issue by tnagler** [JonasMoss/univariateML#41]
There seems to be a bug in `mlnaka()`:
``` r
set.seed(1)
x <- rexp(50)
fit <- mlnaka(x)
fit
#> Maximum likelihood estimates for the Nakagami model 
#> shape   scale  
#> 0.4638  1.7477 

pml(x, fit)
#> Error: 'shape and scale are not valid parameter vectors
```
As far as I understand, the shape parameter must be >= 0.5, but that's not ensured by the fitting procedure.

**Comment by JonasMoss** [comment]
After looking at this for 20 minutes, I must say I don't understand why shape >= 0.5 is demanded (by e.g. wikipedia). It seems to me that m > 0 is possible.  Indeed, defining

```
f = function (x, shape, scale, log = FALSE) {
  rate = 1/scale
  2 * x * stats::dgamma(x = x^2, shape = shape, rate = rate, log = FALSE)
}
```
and running
```
> integrate(f, lower = 0, upper = Inf, shape = 0.1, scale = 2)
1 with absolute error < 0.00011
```

According to the paper http://www.radioeng.cz/fulltexts/2004/04_01_08_12.pdf
" In radio channels modeling, the parameter m is constrained so that m ≥ 1/2 [2]. But this condition may be violated in ultrasound applications [6], [7]. "

And this issue looks more like a bug in `nakagami` to me...

**Comment by JonasMoss** [comment]
I'll update the `nakagami` package and will remove the artifical m <= 0.5 bound.
